# Generated by Django 5.2.4 on 2025-07-09 01:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nama Fasilitas')),
            ],
            options={
                'verbose_name': 'Fasilitas',
                'verbose_name_plural': 'Fasilitas',
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nama Hotel')),
                ('location', models.CharField(max_length=200, verbose_name='Lokasi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Deskripsi')),
                ('average_rating', models.FloatField(default=0.0, verbose_name='Rating Rata-rata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
            ],
            options={
                'verbose_name': 'Hotel',
                'verbose_name_plural': 'Hotel',
            },
        ),
        migrations.CreateModel(
            name='HotelGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hotel_images/', verbose_name='Gambar')),
                ('caption', models.CharField(blank=True, max_length=200, null=True, verbose_name='Keterangan')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='reservasi_backend.hotel', verbose_name='Hotel')),
            ],
            options={
                'verbose_name': 'Galeri Hotel',
                'verbose_name_plural': 'Galeri Hotel',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField(verbose_name='Tanggal Check-in')),
                ('check_out', models.DateField(verbose_name='Tanggal Check-out')),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total Harga')),
                ('status', models.CharField(choices=[('PENDING', 'Menunggu Pembayaran'), ('PAID', 'Dibayar'), ('CHECKED_IN', 'Check-in'), ('CHECKED_OUT', 'Check-out'), ('CANCELLED', 'Dibatalkan')], default='PENDING', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dipesan Pada')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Pemesan')),
            ],
            options={
                'verbose_name': 'Reservasi',
                'verbose_name_plural': 'Reservasi',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('BANK_TRANSFER', 'Transfer Bank'), ('CREDIT_CARD', 'Kartu Kredit'), ('E_WALLET', 'Dompet Digital')], default='BANK_TRANSFER', max_length=50, verbose_name='Metode Pembayaran')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Lunas')),
                ('proof', models.ImageField(blank=True, null=True, upload_to='payment_proofs/', verbose_name='Bukti Pembayaran')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Dibayar Pada')),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reservasi_backend.reservation', verbose_name='Reservasi')),
            ],
            options={
                'verbose_name': 'Pembayaran',
                'verbose_name_plural': 'Pembayaran',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Rating (1-5)')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Komentar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Ulasan')),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reservasi_backend.reservation', verbose_name='Reservasi')),
            ],
            options={
                'verbose_name': 'Ulasan',
                'verbose_name_plural': 'Ulasan',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, unique=True, verbose_name='Nomor Kamar')),
                ('is_available', models.BooleanField(default=True, verbose_name='Tersedia')),
                ('facilities', models.ManyToManyField(blank=True, to='reservasi_backend.facility', verbose_name='Fasilitas')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='reservasi_backend.hotel', verbose_name='Hotel')),
            ],
            options={
                'verbose_name': 'Kamar',
                'verbose_name_plural': 'Kamar',
            },
        ),
        migrations.AddField(
            model_name='reservation',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='reservasi_backend.room', verbose_name='Kamar'),
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nama Tipe Kamar')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Deskripsi')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Harga per Malam')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_types', to='reservasi_backend.hotel', verbose_name='Hotel')),
            ],
            options={
                'verbose_name': 'Tipe Kamar',
                'verbose_name_plural': 'Tipe Kamar',
            },
        ),
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservasi_backend.roomtype', verbose_name='Tipe Kamar'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Nomor Telepon')),
                ('gender', models.CharField(choices=[('M', 'Laki-laki'), ('F', 'Perempuan')], default='M', max_length=1, verbose_name='Jenis Kelamin')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Alamat')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Pengguna')),
            ],
            options={
                'verbose_name': 'Profil Pengguna',
                'verbose_name_plural': 'Profil Pengguna',
            },
        ),
    ]
