# Generated by Django 5.2.4 on 2025-07-09 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservasi_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='region',
            field=models.CharField(choices=[('Lampung', 'Lampung'), ('Jakarta', 'Jakarta'), ('Surabaya', 'Surabaya')], default='jakarta', max_length=200, verbose_name='Region'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='base_price',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Harga per Malam'),
        ),
    ]
