# Generated by Django 5.2.4 on 2025-07-19 18:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservasi_backend', '0002_hotel_region_alter_roomtype_base_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='star_rating',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Rating Bintang (0-5)'),
        ),
    ]
