# Generated by Django 5.2.3 on 2025-06-30 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservasi_backend', '0002_facility_roomtype_alter_userprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ImageField(default=1, upload_to='room_images/'),
            preserve_default=False,
        ),
    ]
