# Generated by Django 5.2.3 on 2025-06-30 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservasi_backend', '0003_room_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='image',
        ),
        migrations.AddField(
            model_name='roomtype',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='room_types/'),
        ),
    ]
