# Generated by Django 5.2.4 on 2025-07-23 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservasi_backend', '0003_hotel_star_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Kode Pembayaran (VA)'),
        ),
    ]
