# Generated by Django 5.2.3 on 2025-07-04 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservasi_backend', '0004_remove_room_image_roomtype_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nama Hotel')),
                ('description', models.TextField(blank=True, verbose_name='Deskripsi')),
                ('address', models.TextField(verbose_name='Alamat')),
                ('city', models.CharField(max_length=100, verbose_name='Kota')),
                ('province', models.CharField(max_length=100, verbose_name='Provinsi')),
                ('rating', models.PositiveSmallIntegerField(default=0, verbose_name='Rating (1-5)')),
                ('image_cover', models.ImageField(blank=True, null=True, upload_to='hotels/', verbose_name='Gambar Utama')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Hotel',
                'verbose_name_plural': 'Hotel',
            },
        ),
        migrations.AddField(
            model_name='room',
            name='hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reservasi_backend.hotel', verbose_name='Hotel'),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='hotel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reservasi_backend.hotel', verbose_name='Hotel'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='HotelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hotel_images/', verbose_name='Gambar')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Keterangan')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='reservasi_backend.hotel', verbose_name='Hotel')),
            ],
            options={
                'verbose_name': 'Gambar Hotel',
                'verbose_name_plural': 'Gambar Hotel',
            },
        ),
    ]
