# Generated by Django 5.2.4 on 2025-07-23 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservasi_backend', '0004_payment_payment_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('BANK_TRANSFER', 'Transfer Bank'), ('CREDIT_CARD', 'Kartu Kredit'), ('E_WALLET', 'Dompet Digital'), ('MIDTRANS', 'Midtrans Snap')], default='MIDTRANS', max_length=50, verbose_name='Metode Pembayaran'),
        ),
    ]
