# Generated by Django 5.2.3 on 2025-07-04 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservasi_backend', '0005_hotel_room_hotel_roomtype_hotel_hotelimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='facilities',
            field=models.ManyToManyField(blank=True, related_name='hotels', to='reservasi_backend.facility', verbose_name='Fasilitas'),
        ),
    ]
