# Generated by Django 5.2.4 on 2025-07-25 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservasi_backend', '0005_alter_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_code',
        ),
        migrations.AddField(
            model_name='reservation',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='first_name',
            field=models.CharField(default='Guest', max_length=30, verbose_name='Nama Depan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='last_name',
            field=models.CharField(default='User', max_length=30, verbose_name='Nama Belakang'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Nomor Telepon'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='special_request',
            field=models.TextField(blank=True, null=True, verbose_name='Permintaan Khusus'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('BANK_TRANSFER', 'Transfer Bank'), ('E_WALLET', 'Dompet Digital')], default='BANK_TRANSFER', max_length=50, verbose_name='Metode Pembayaran'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='base_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Harga per Malam'),
        ),
    ]
